version: "3.8"

services:
  # === PROD BACKEND ===
  backend-prod:
    build:
      context: ./server
      dockerfile: Dockerfile
      args:
        NODE_ENV: production
    container_name: upload-be-prod
    environment:
      - NODE_ENV=production
      - DB_HOST=192.168.55.5
      - DB_PORT=5435
      - DB_USER=mitaka
      - DB_PASSWORD=mitaka
      - DB_NAME=prod_db
      - ALLOWED_ORIGIN=https://upload.d-dimitrov.eu
    volumes:
      - ./server:/app
      - /ssd/docker/mitaka-website/mitaka-website/upload:/app/upload
      - ./....env.production:/app/....env.production
      - ./....env.development:/app/....env.development
    restart: always

  # === PROD FRONTEND ===
  frontend-prod:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: production
    container_name: upload-fe-prod
    depends_on:
      - backend-prod
    environment:
      - NODE_ENV=production
    volumes:
      - /ssd/docker/mitaka-website/mitaka-website/upload:/app/upload
    restart: always

networks:
  default:
    external:
      name: docker_network
