version: "3.8"

services:
  # === PROD BACKEND ===
  backend-prod:
    build:
      context: ./server
      dockerfile: Dockerfile
      args:
        NODE_ENV: production
    container_name: upload-be-prod
    ports:
      - "3400:3400"
    env_file:
      - ./server/.env.production  # Docker ще зареди променливите автоматично
    volumes:
    - ./server:/app
    - /app/node_modules
    - ./server/.env.production:/app/.env.production
    - /ssd/docker/mitaka-website/mitaka-website/upload:/app/upload
    restart: always

  # === PROD FRONTEND ===
  frontend-prod:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: production
    container_name: upload-fe-prod
    env_file:
      - .env.production
    ports:
      - "3500:80"
    depends_on:
      - backend-prod
    environment:
      - NODE_ENV=production
    volumes:
      - /ssd/docker/mitaka-website/mitaka-website/upload:/app/upload
    restart: always

networks:
  default:
    external:
      name: docker_network
